minio.url=${MINIO_URL:http://localhost}:${MINIO_PORT:9000}
minio.access-key=${MINIO_USERNAME:minioadmin}
minio.secret-key=${MINIO_PASSWORD:minioadmin}
minio.bucket.name.attachments=attachments
minio.bucket.name.profile-pictures=profile-pictures